(function () {
  "use strict";
  var previews = {
    websites:{n:"01 / 05",s:"WEBSITES · PROJECT PREVIEW",t:"WEBSITES",h:"Porch Stomp Festival website.",d:"A festival website reorganized so visitors can find the schedule, stages, and lineup from a phone.",i:"assets/Porch Stomp Screenshot.png",a:"Porch Stomp Festival website screenshot",u:"work/websites/"},
    nonprofits:{n:"02 / 05",s:"NONPROFITS & PROGRAMS · PROJECT PREVIEW",t:"NONPROFITS & PROGRAMS",h:"Discovery Sound Garden.",d:"A nonprofit built around music education, recording access, fundraising, partnerships, and a public website.",i:"assets/DSG Social Share.jpg",a:"Discovery Sound Garden project image",u:"work/nonprofits-programs/"},
    campaigns:{n:"03 / 05",s:"SOCIAL MEDIA & CAMPAIGNS · PROJECT PREVIEW",t:"SOCIAL MEDIA & CAMPAIGNS",h:"Atlantic Theater Company social edits.",d:"Campaign videos edited in horizontal and vertical versions for the social feeds where the theater's audience would see them.",i:"assets/social-feed-poster.jpg",a:"Atlantic Theater Company campaign video poster",u:"work/campaigns-content/"},
    media:{n:"04 / 05",s:"AUDIO, VIDEO & MUSIC · PROJECT PREVIEW",t:"AUDIO, VIDEO & MUSIC",h:"Dance mixes, video edits, and live sets.",d:"Hear finished audio, browse edited videos, or see live music options for events and performances.",i:"assets/video-poster-3.jpg",a:"Rooftop Ramblers performance poster",u:"work/media/"},
    workflows:{n:"05 / 05",s:"WORKFLOWS · PROJECT PREVIEW",t:"WORKFLOWS",h:"Booking research and everyday systems.",d:"Booking lists, grant research, website audits, meal plans, and computer setup.",i:"assets/andrew-ai-idea.png",a:"Andrew with a light bulb",u:"work/workflows/"}
  };
  function revealPlayer(selector){if(matchMedia("(max-width:760px)").matches)document.querySelector(selector)?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion:reduce)").matches?"auto":"smooth",block:"start"});}
  function setText(id, value) { var el = document.getElementById(id); if (el) el.textContent = value; }
  function showPreview(key) {
    var item = previews[key]; if (!item) return;
    setText("previewStatus",item.s); setText("projectionNumber",item.n); setText("projectionType",item.t); setText("projectionTitle",item.h); setText("projectionDescription",item.d);
    var image = document.getElementById("projectionImage"), link = document.getElementById("projectionLink");
    if (image) { image.src=item.i; image.alt=item.a; }
    if (link) { link.href=item.u; link.textContent=({websites:"See website projects",nonprofits:"See Discovery Sound Garden",campaigns:"See social media campaigns",media:"Open audio, video & music",workflows:"Explore workflow examples"})[key]; }
    document.querySelectorAll("[data-work-preview]").forEach(function(button){button.classList.toggle("is-current",button.dataset.workPreview===key);button.setAttribute("aria-pressed",String(button.dataset.workPreview===key));});
  }
  document.querySelectorAll("[data-work-preview]").forEach(function(button){
 button.removeAttribute("role");button.setAttribute("aria-pressed",String(button.classList.contains("is-current")));
 button.addEventListener("click",function(){showPreview(button.dataset.workPreview);if(matchMedia("(max-width:760px)").matches)document.querySelector(".projection").scrollIntoView({behavior:matchMedia("(prefers-reduced-motion:reduce)").matches?"auto":"smooth",block:"start"});});
});
  document.querySelectorAll("[data-dialog-open]").forEach(function(trigger){trigger.addEventListener("click",function(){var dialog=document.getElementById(trigger.dataset.dialogOpen);if(dialog&&dialog.showModal)dialog.showModal();});});
  document.querySelectorAll("dialog").forEach(function(dialog){dialog.querySelectorAll("[data-dialog-close]").forEach(function(button){button.addEventListener("click",function(){dialog.close();});});dialog.addEventListener("click",function(event){if(event.target===dialog)dialog.close();});});
  var channels=document.querySelectorAll("[data-media-channel]");
function stopMedia(){document.querySelectorAll("audio,video").forEach(function(m){m.pause();});var frame=document.querySelector("#liveScreen iframe");if(frame){renderLive();}}

  function chooseChannel(name, updateHash) {
    stopMedia();
    channels.forEach(function(button){var active=button.dataset.mediaChannel===name;button.classList.toggle("is-active",active);button.setAttribute("aria-selected",String(active));button.tabIndex=active?0:-1;});
    document.querySelectorAll("[data-media-panel]").forEach(function(panel){panel.hidden=panel.dataset.mediaPanel!==name;});
    setText("activeChannelLabel","NOW SHOWING: "+(name==="live"?"LIVE MUSIC":name.toUpperCase()));
    if(updateHash)history.replaceState(null,"","#"+name);
  }
  if(channels.length){
    channels.forEach(function(button){button.addEventListener("click",function(){chooseChannel(button.dataset.mediaChannel,true);});});
    var initial=location.hash.slice(1);chooseChannel(["audio","video","live"].indexOf(initial)>-1?initial:"audio",false);
    window.addEventListener("hashchange",function(){var name=location.hash.slice(1);if(["audio","video","live"].indexOf(name)>-1)chooseChannel(name,false);});
  }
  document.querySelectorAll("[data-audio-proof]").forEach(function(audio){audio.addEventListener("play",function(){audio.closest(".soundcheck-panel").classList.add("is-playing");});["pause","ended"].forEach(function(eventName){audio.addEventListener(eventName,function(){audio.closest(".soundcheck-panel").classList.remove("is-playing");});});});
  document.querySelectorAll("[data-audio-src]").forEach(function(button){button.addEventListener("click",function(){var audio=document.getElementById("audioProof");if(!audio)return;audio.src=button.dataset.audioSrc;audio.load();setText("audioName",button.dataset.audioName);document.querySelectorAll("[data-audio-src]").forEach(function(item){item.classList.toggle("is-selected",item===button);});});});
  document.querySelectorAll("[data-video-src]").forEach(function(button){button.addEventListener("click",function(){var video=document.getElementById("videoProof");if(!video)return;video.src=button.dataset.videoSrc;video.poster=button.dataset.videoPoster;video.load();setText("videoName",button.dataset.videoName);setText("videoDescription",button.dataset.videoDescription);document.querySelectorAll("[data-video-src]").forEach(function(item){item.classList.toggle("is-selected",item===button);});});});

const recordings=[["Full Dance Mix","Full Dance Mix.mp3","Dance performance mix"],["Quince Example Clips","Quince Example Clips.mp3","Event entrances and transitions"],["Bourbon Bar Podcast","Bourbon Bar Podast.mp3","Podcast editing and mixing"],["Hip Hop Dance Mixes","Example Hip Hop Dance Mixes.mp3","Dance cutdowns and mashups"]], videos=[["Ultimate Reel","Ultimate Reel.mp4","video-poster-1.jpg","Showreel"],["Break My Stride","BDT Break My Stride 2020.mp4","video-poster-2.jpg","2020 dance performance edit"],["Rooftop Ramblers","rooftop-ramblers.mp4","video-poster-3.jpg","Band promotional video"],["Birthday Montage","Mom Bday Video.mp4","video-poster-4.jpg","Personal birthday montage"]], performances=[["E8y4BYpBVcY","Man or Muppet","Live at The Reverie Room"],["1mIcwHTqlK0","El Tango de Britney","…Baby One More Time tango cover · The Reverie Room"],["qCm7FZ3GZdU","Sad Singin’ & Slow Ridin’","Andrew Wolverton · Mr. Hoosier"]];
let audioIndex=0, videoIndex=0, liveIndex=0;
function selectAudio(i){audioIndex=(i+recordings.length)%recordings.length;const item=recordings[audioIndex],player=document.getElementById("audioProof");player.pause();player.src="../../assets/"+item[1];player.load();setText("audioToggle","Play");setText("audioName",item[0]);setText("audioContext",item[2]);document.querySelectorAll("[data-audio-index]").forEach(b=>b.setAttribute("aria-pressed",String(+b.dataset.audioIndex===audioIndex)));}
document.querySelectorAll("[data-audio-index]").forEach(b=>b.addEventListener("click",()=>selectAudio(+b.dataset.audioIndex)));
const player=document.getElementById("audioProof");
if(player){document.getElementById("audioPrevious").onclick=()=>selectAudio(audioIndex-1);document.getElementById("audioNext").onclick=()=>selectAudio(audioIndex+1);document.getElementById("audioToggle").onclick=()=>{if(player.paused)player.play().catch(()=>setText("audioContext","Playback could not start. Try the player controls."));else player.pause();};["play","pause","ended","emptied"].forEach(e=>player.addEventListener(e,()=>setText("audioToggle",player.paused?"Play":"Pause")));}
document.querySelectorAll("[data-video-index]").forEach(b=>b.addEventListener("click",()=>{const i=+b.dataset.videoIndex,item=videos[i],v=document.getElementById("videoProof");stopMedia();v.src="../../assets/"+item[1];v.poster="../../assets/"+item[2];v.load();setText("videoName",item[0]);setText("videoContext",item[3]);document.querySelectorAll("[data-video-index]").forEach(x=>x.setAttribute("aria-pressed",String(x===b)));revealPlayer(".rental-player");}));
function renderLive(){const screen=document.getElementById("liveScreen");if(!screen)return;const item=performances[liveIndex];screen.innerHTML='<button class="live-poster" id="playLive" aria-label="Play selected performance"><img src="https://i.ytimg.com/vi/'+item[0]+'/maxresdefault.jpg" alt=""><span>▶ Play performance</span></button>';document.getElementById("playLive").onclick=()=>{document.querySelectorAll("audio,video").forEach(m=>m.pause());screen.innerHTML='<iframe title="'+item[1]+'" src="https://www.youtube-nocookie.com/embed/'+item[0]+'?autoplay=1&rel=0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>';};}
document.querySelectorAll("[data-live-index]").forEach(b=>b.addEventListener("click",()=>{stopMedia();liveIndex=+b.dataset.liveIndex;const item=performances[liveIndex];setText("liveTitle",item[1]);setText("liveContext",item[2]);document.getElementById("liveDirect").href="https://www.youtube.com/watch?v="+item[0];document.querySelectorAll("[data-live-index]").forEach(x=>x.setAttribute("aria-pressed",String(x===b)));renderLive();revealPlayer(".live-heading");}));
if(document.getElementById("liveScreen"))renderLive();
const workflows={"booking":{"title":"Rooftop Ramblers booking research","input":"Venue websites, booking contacts, past outreach, and notes about the band.","task":"Andrew checks the venue, chooses who to contact, and approves the message.","output":"A booking list with each venue’s contact, fit, last conversation, and next step.","rows":[["Example venue","Booking contact","Next step"],["Brooklyn venue","Contact on venue website","Check music schedule"],["Past booking","Previous email thread","Draft follow-up"]]},"fundraising":{"title":"Discovery Sound Garden grant research","input":"Funder guidelines, program descriptions, budgets, and previous applications.","task":"Andrew checks eligibility, confirms evidence, and decides which opportunities to pursue.","output":"A grant brief with requirements, deadlines, source links, and missing materials.","rows":[["Requirement","Source","Action"],["Program eligibility","Funder guidelines","Confirm fit"],["Project budget","Application instructions","Prepare budget"]]},"website":{"title":"Website audit and repair planning","input":"Existing pages, client feedback, broken links, and design references.","task":"Andrew chooses the navigation, edits the content, and tests the finished pages.","output":"A page inventory and prioritized repair list that guide the website build.","rows":[["Page","Issue","Next step"],["Home","Unclear destination","Rewrite navigation"],["Contact","Form needs checking","Test submission"]]},"grocery":{"title":"Weekly meal planning","input":"Food already at home, the week’s schedule, budget, and food preferences.","task":"Andrew chooses the meals and confirms the grocery list.","output":"A short meal plan and shopping list that reuse ingredients already on hand.","rows":[["Meal","Use at home","Buy"],["Rice bowl","Rice and vegetables","Protein"],["Work lunch","Dinner leftovers","Nothing extra"]]},"adhd":{"title":"Computer setup for everyday tasks","input":"Repeated setup steps, scattered files, reminders, and frequently used applications.","task":"Andrew chooses the shortcuts and checks that files and routines work as expected.","output":"A small set of shortcuts for starting work, finding files, and resuming a task.","rows":[["Task","Starting point","Action"],["Begin work","Workspace shortcut","Open needed apps"],["Find a download","File review list","Choose a destination"]]}};
function workflow(key){let w=workflows[key];if(!w)return;setText("workflowTitle",w.title);setText("workflowInput",w.input);setText("workflowTask",w.task);setText("workflowOutput",w.output);document.getElementById("workflowTable").innerHTML='<table><thead><tr>'+w.rows[0].map(t=>'<th scope="col">'+t+'</th>').join('')+'</tr></thead><tbody>'+w.rows.slice(1).map(r=>'<tr>'+r.map(t=>'<td>'+t+'</td>').join('')+'</tr>').join('')+'</tbody></table>';document.querySelectorAll("[data-workflow]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.workflow===key)));}
document.querySelectorAll("[data-workflow]").forEach(b=>b.addEventListener("click",()=>workflow(b.dataset.workflow)));if(document.getElementById("workflowTable"))workflow("booking");
const socialPosts=[["Cnke46IN1EY","Atlantic Theater Company","Horizontal campaign video","Editing and adaptation for a horizontal social post."],["CoFyIzwssNR","Atlantic Theater Company","Vertical campaign video","Editing and adaptation for a vertical social post."],["CwDbBv9PD-4","Terry Knickerbocker Studio","Promotional social video","Promotional video editing for the acting studio."]];
document.querySelectorAll("[data-social]").forEach(b=>b.addEventListener("click",()=>{let p=socialPosts[+b.dataset.social];setText("socialClient",p[1]);setText("socialPreviewTitle",p[1]+" · "+p[2]);document.getElementById("socialPreviewLink").href="https://www.instagram.com/reel/"+p[0]+"/";document.getElementById("socialEmbed").hidden=true;document.getElementById("loadSocial").setAttribute("aria-expanded","false");setText("loadSocial","Load post here");setText("socialTitle",p[2]);setText("socialRole",p[3]);document.querySelector("#socialEmbed iframe").src="https://www.instagram.com/reel/"+p[0]+"/embed/";document.querySelector("#socialEmbed iframe").title=p[1]+" "+p[2];document.getElementById("socialDirect").href="https://www.instagram.com/reel/"+p[0]+"/";document.querySelectorAll("[data-social]").forEach(x=>x.setAttribute("aria-pressed",String(x===b)));}));
const loadSocial=document.getElementById("loadSocial");if(loadSocial)loadSocial.addEventListener("click",()=>{const box=document.getElementById("socialEmbed");box.hidden=!box.hidden;loadSocial.setAttribute("aria-expanded",String(!box.hidden));loadSocial.textContent=box.hidden?"Load post here":"Hide embedded post";});
channels.forEach((b,i)=>b.addEventListener("keydown",e=>{let j=e.key==="ArrowRight"?(i+1)%channels.length:e.key==="ArrowLeft"?(i+channels.length-1)%channels.length:e.key==="Home"?0:e.key==="End"?channels.length-1:-1;if(j<0)return;e.preventDefault();channels[j].focus();chooseChannel(channels[j].dataset.mediaChannel,true);}));
var doon=document.getElementById("doonGuide"); if(doon)doon.addEventListener("click",function(){doon.setAttribute("aria-expanded",String(doon.getAttribute("aria-expanded")!=="true"));});
  if(document.body.classList.contains("workroom-index")){
    var query=new URLSearchParams(location.search), project=query.get("project"), media=query.get("media"), focus=query.get("focus"), hash=location.hash.toLowerCase(), target="";
    if(project==="porch-stomp"||project==="yolele")target="work/websites/"; else if(project==="dsg")target="work/nonprofits-programs/"; else if(media==="audio"||media==="video"||media==="performance")target="work/media/#"+(media==="performance"?"live":media); else if(hash==="#dsgdeepdive")target="work/nonprofits-programs/"; else if(focus==="ai"||hash==="#ai")target="work/workflows/"; else if(["#projects","#websites","#websitework"].indexOf(hash)>-1)target="work/websites/"; else if(["#media","#audio","#video","#performance"].indexOf(hash)>-1)target="work/media/#"+(hash==="#performance"?"live":hash==="#media"?"audio":hash.slice(1));
    if(target)location.replace(target);
  }
}());
